# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: NPM install
        run: |
          npm ci
      - name: Lint JavaScript
        run: |
          npm run lint:js
      - name: Unit tests
        run: |
          npm run test:ci